[build]
  base = "/"
  publish = "dist/countdown/browser"
  command = "npm run ci:env && npm run build countdown"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF projects/countdown"

[[redirects]]
  from = "https://cocco-countdown.netlify.app/*"
  to = "https://countdown.smallbytes.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
